//===========================================================================
// Header File Generated by Script. Do NOT change manually!
//===========================================================================

#ifndef ABOUT_CRC32_H
#define ABOUT_CRC32_H
    #ifndef ABOUT_CRC32
        #define ABOUT_CRC32 0xf070cee8
    #endif
#endif
